// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: caffe.sql

package db

import (
	"context"
	"database/sql"
)

const createCafe = `-- name: CreateCafe :one
INSERT INTO cafes (name, city, rating)
VALUES ($1, $2, $3)
RETURNING id, name, city, address, description, rating, created_at
`

type CreateCafeParams struct {
	Name   string
	City   string
	Rating sql.NullFloat64
}

func (q *Queries) CreateCafe(ctx context.Context, arg CreateCafeParams) (Cafe, error) {
	row := q.db.QueryRowContext(ctx, createCafe, arg.Name, arg.City, arg.Rating)
	var i Cafe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Address,
		&i.Description,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const getAllCafes = `-- name: GetAllCafes :many
SELECT id, name, city, address, description, rating, created_at
FROM cafes
LIMIT $1 OFFSET $2
`

type GetAllCafesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllCafes(ctx context.Context, arg GetAllCafesParams) ([]Cafe, error) {
	rows, err := q.db.QueryContext(ctx, getAllCafes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cafe
	for rows.Next() {
		var i Cafe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Address,
			&i.Description,
			&i.Rating,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCafeByID = `-- name: GetCafeByID :one
SELECT id, name, city, address, description, rating, created_at
FROM cafes
WHERE id = $1
`

func (q *Queries) GetCafeByID(ctx context.Context, id int32) (Cafe, error) {
	row := q.db.QueryRowContext(ctx, getCafeByID, id)
	var i Cafe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Address,
		&i.Description,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const getCafes = `-- name: GetCafes :many
SELECT id, name, city, address, description, rating, created_at
FROM cafes
`

func (q *Queries) GetCafes(ctx context.Context) ([]Cafe, error) {
	rows, err := q.db.QueryContext(ctx, getCafes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cafe
	for rows.Next() {
		var i Cafe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Address,
			&i.Description,
			&i.Rating,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCaffesByCity = `-- name: GetCaffesByCity :many
SELECT id, name, city, address, description, rating, created_at
FROM cafes
WHERE city ILIKE $1
LIMIT $2 OFFSET $3
`

type GetCaffesByCityParams struct {
	City   string
	Limit  int32
	Offset int32
}

func (q *Queries) GetCaffesByCity(ctx context.Context, arg GetCaffesByCityParams) ([]Cafe, error) {
	rows, err := q.db.QueryContext(ctx, getCaffesByCity, arg.City, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cafe
	for rows.Next() {
		var i Cafe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Address,
			&i.Description,
			&i.Rating,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCafe = `-- name: UpdateCafe :one
UPDATE cafes
SET name = $2,
    city = $3,
    rating = $4
WHERE id = $1
RETURNING id, name, city, address, description, rating, created_at
`

type UpdateCafeParams struct {
	ID     int32
	Name   string
	City   string
	Rating sql.NullFloat64
}

func (q *Queries) UpdateCafe(ctx context.Context, arg UpdateCafeParams) (Cafe, error) {
	row := q.db.QueryRowContext(ctx, updateCafe,
		arg.ID,
		arg.Name,
		arg.City,
		arg.Rating,
	)
	var i Cafe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Address,
		&i.Description,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}
