// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: caffe.sql

package db

import (
	"context"
	"database/sql"
)

const createCafe = `-- name: CreateCafe :one
INSERT INTO cafes (name, city, rating)
VALUES ($1, $2, $3)
RETURNING id, name, tagline, address, city, latitude, longitude, open_hours, phone, instagram, rating, reviews, price_level, hero_img, vibe_emoji, created_at, updated_at
`

type CreateCafeParams struct {
	Name   string
	City   sql.NullString
	Rating sql.NullString
}

func (q *Queries) CreateCafe(ctx context.Context, arg CreateCafeParams) (Cafe, error) {
	row := q.db.QueryRowContext(ctx, createCafe, arg.Name, arg.City, arg.Rating)
	var i Cafe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tagline,
		&i.Address,
		&i.City,
		&i.Latitude,
		&i.Longitude,
		&i.OpenHours,
		&i.Phone,
		&i.Instagram,
		&i.Rating,
		&i.Reviews,
		&i.PriceLevel,
		&i.HeroImg,
		&i.VibeEmoji,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllCafes = `-- name: GetAllCafes :many
SELECT id, name, tagline, address, city, latitude, longitude, open_hours, phone, instagram, rating, reviews, price_level, hero_img, vibe_emoji, created_at, updated_at
FROM cafes
LIMIT $1 OFFSET $2
`

type GetAllCafesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllCafes(ctx context.Context, arg GetAllCafesParams) ([]Cafe, error) {
	rows, err := q.db.QueryContext(ctx, getAllCafes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cafe
	for rows.Next() {
		var i Cafe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tagline,
			&i.Address,
			&i.City,
			&i.Latitude,
			&i.Longitude,
			&i.OpenHours,
			&i.Phone,
			&i.Instagram,
			&i.Rating,
			&i.Reviews,
			&i.PriceLevel,
			&i.HeroImg,
			&i.VibeEmoji,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCafeByID = `-- name: GetCafeByID :one
SELECT id, name, tagline, address, city, latitude, longitude, open_hours, phone, instagram, rating, reviews, price_level, hero_img, vibe_emoji, created_at, updated_at
FROM cafes
WHERE id = $1
`

func (q *Queries) GetCafeByID(ctx context.Context, id int32) (Cafe, error) {
	row := q.db.QueryRowContext(ctx, getCafeByID, id)
	var i Cafe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tagline,
		&i.Address,
		&i.City,
		&i.Latitude,
		&i.Longitude,
		&i.OpenHours,
		&i.Phone,
		&i.Instagram,
		&i.Rating,
		&i.Reviews,
		&i.PriceLevel,
		&i.HeroImg,
		&i.VibeEmoji,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCafesByCity = `-- name: GetCafesByCity :many
SELECT id, name, tagline, address, city, latitude, longitude, open_hours, phone, instagram, rating, reviews, price_level, hero_img, vibe_emoji, created_at, updated_at
FROM cafes
WHERE city ILIKE $1
LIMIT $2 OFFSET $3
`

type GetCafesByCityParams struct {
	City   sql.NullString
	Limit  int32
	Offset int32
}

func (q *Queries) GetCafesByCity(ctx context.Context, arg GetCafesByCityParams) ([]Cafe, error) {
	rows, err := q.db.QueryContext(ctx, getCafesByCity, arg.City, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cafe
	for rows.Next() {
		var i Cafe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tagline,
			&i.Address,
			&i.City,
			&i.Latitude,
			&i.Longitude,
			&i.OpenHours,
			&i.Phone,
			&i.Instagram,
			&i.Rating,
			&i.Reviews,
			&i.PriceLevel,
			&i.HeroImg,
			&i.VibeEmoji,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCafe = `-- name: UpdateCafe :one
UPDATE cafes
SET name = $2,
    city = $3,
    rating = $4
WHERE id = $1
RETURNING id, name, tagline, address, city, latitude, longitude, open_hours, phone, instagram, rating, reviews, price_level, hero_img, vibe_emoji, created_at, updated_at
`

type UpdateCafeParams struct {
	ID     int32
	Name   string
	City   sql.NullString
	Rating sql.NullString
}

func (q *Queries) UpdateCafe(ctx context.Context, arg UpdateCafeParams) (Cafe, error) {
	row := q.db.QueryRowContext(ctx, updateCafe,
		arg.ID,
		arg.Name,
		arg.City,
		arg.Rating,
	)
	var i Cafe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tagline,
		&i.Address,
		&i.City,
		&i.Latitude,
		&i.Longitude,
		&i.OpenHours,
		&i.Phone,
		&i.Instagram,
		&i.Rating,
		&i.Reviews,
		&i.PriceLevel,
		&i.HeroImg,
		&i.VibeEmoji,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
