// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: facilities.sql

package db

import (
	"context"
)

const getFacilitiesByCafeID = `-- name: GetFacilitiesByCafeID :many
select f.id,
    f.name
from cafes c
    inner join cafe_facilities cf on cf.cafe_id = c.id
    inner join facilities f on f.id = cf.facility_id
where c.id = $1
`

type GetFacilitiesByCafeIDRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetFacilitiesByCafeID(ctx context.Context, id int32) ([]GetFacilitiesByCafeIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getFacilitiesByCafeID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFacilitiesByCafeIDRow
	for rows.Next() {
		var i GetFacilitiesByCafeIDRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
