// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menu.sql

package db

import (
	"context"
	"database/sql"
)

const getMenusByCafeID = `-- name: GetMenusByCafeID :many
select m.id,
    m.cafe_id,
    m.name,
    m.price,
    m.strength,
    m.is_safe,
    m.description,
    m.image
from menus m
where m.cafe_id = $1
`

type GetMenusByCafeIDRow struct {
	ID          int32
	CafeID      int32
	Name        string
	Price       int32
	Strength    sql.NullInt32
	IsSafe      sql.NullBool
	Description sql.NullString
	Image       sql.NullString
}

func (q *Queries) GetMenusByCafeID(ctx context.Context, cafeID int32) ([]GetMenusByCafeIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getMenusByCafeID, cafeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMenusByCafeIDRow
	for rows.Next() {
		var i GetMenusByCafeIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CafeID,
			&i.Name,
			&i.Price,
			&i.Strength,
			&i.IsSafe,
			&i.Description,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
