// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Cafe struct {
	ID             int32
	Name           string
	Tagline        sql.NullString
	Address        sql.NullString
	City           sql.NullString
	Latitude       sql.NullString
	Longitude      sql.NullString
	OpenHours      sql.NullString
	Phone          sql.NullString
	Instagram      sql.NullString
	Rating         sql.NullString
	Reviews        sql.NullInt32
	PriceLevel     sql.NullInt32
	HeroImg        sql.NullString
	VibeEmoji      sql.NullString
	Approved       sql.NullBool
	ApprovedReason sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
}

type CafeApproval struct {
	ID             int32
	CafeID         sql.NullInt32
	Approved       sql.NullBool
	ApprovedReason sql.NullString
	ApprovedAt     sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
}

type CafeFacility struct {
	CafeID     int32
	FacilityID int32
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
}

type CafeTag struct {
	CafeID    int32
	TagID     int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Facility struct {
	ID        int32
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Menu struct {
	ID          int32
	CafeID      int32
	Name        string
	Price       int32
	Strength    sql.NullInt32
	IsSafe      sql.NullBool
	Description sql.NullString
	Image       sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type Photo struct {
	ID        int32
	IsPrimary sql.NullBool
	Position  sql.NullInt32
	CafeID    int32
	Url       string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Tag struct {
	ID        int32
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
