// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Cafe struct {
	ID          int32
	Name        string
	City        string
	Address     sql.NullString
	Description sql.NullString
	Rating      sql.NullFloat64
	CreatedAt   sql.NullTime
}

type Menu struct {
	ID          int32
	CafeID      int32
	Name        string
	Price       int32
	Description sql.NullString
	CreatedAt   sql.NullTime
}

type Photo struct {
	ID        int32
	CafeID    int32
	Url       string
	CreatedAt sql.NullTime
}

type Review struct {
	ID        int32
	CafeID    int32
	Name      sql.NullString
	Rating    sql.NullInt32
	Comment   sql.NullString
	CreatedAt sql.NullTime
}
