// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"
)

const getTagsByCafeID = `-- name: GetTagsByCafeID :many
select t."name",
    t.id
from cafes c
    inner join cafe_tags ct on ct.cafe_id = c.id
    inner join tags t on t.id = ct.tag_id
where c.id = $1
`

type GetTagsByCafeIDRow struct {
	Name string
	ID   int32
}

func (q *Queries) GetTagsByCafeID(ctx context.Context, id int32) ([]GetTagsByCafeIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getTagsByCafeID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagsByCafeIDRow
	for rows.Next() {
		var i GetTagsByCafeIDRow
		if err := rows.Scan(&i.Name, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
